name: Update Sunsetr Version

on:
  push:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release
        id: get_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/psi4j/sunsetr/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(echo '${{ steps.get_release.outputs.data }}' | jq -r '.tag_name' | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update flake.nix
        run: |
          # Update ver in let block only
          sed -i 's/ver = "[^"]*"/ver = "'$VERSION'"/' flake.nix

          # Update x86_64 hash
          x86_64_hash=$(nix-prefetch-url --type sha256 https://github.com/psi4j/sunsetr/releases/download/v${VERSION}/sunsetr-v${VERSION}-x86_64-linux.tar.gz)
          sed -i '/x86_64-linux/,/sha256/s/sha256 = "[^"]*"/sha256 = "'$x86_64_hash'"/' flake.nix
          echo "x86_64 hash: $x86_64_hash"

          cat flake.nix
          nix flake update

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump sunsetr version to ${{ steps.extract_version.outputs.version }}"
